version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-code_reviewer}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/code_reviewer
      PORT: 8000
      REPO_CLONE_DIR: /clonedrepos
    ports:
      - "9000:8000"
    depends_on:
      - db
    volumes:
      - clonedrepos:/clonedrepos
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://localhost:9000}
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  pgdata:
  clonedrepos:
